### ISSUE TITLE
Need the Program Criteria Sheet

### ISSUE THREAD

**Issue by andrewk6** [bkinder42/Team_Name_Semester_Simulator#1]
Someone should type up and upload the criteria sheet for the program so that we can get to work on some of the more basic aspects of the program.  We should also arrange a time to meet and discus stuff.

**Comment by bkinder42** [comment]
[DesignSetup.txt](https://github.com/bkinder42/Team_Name_Semester_Simulator/files/578315/DesignSetup.txt)
